name: Create meeting issue

on:
  schedule:
    - cron: "0 0 * * 3" # run each Wednesday

jobs:
  steps:
    - uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/ISSUE_TEMPLATE/meeting.md